runtime: php55
api_version: 1

handlers:
- url: /
  script: GAMVPA.php
- url: /GA.html
  script: GA.html
- url: /MVPA.html
  script: MVPA.html
- url: /js
  static_dir: js
- url: /style
  static_dir: style
